---
- name: "{{ php_fpm_pool }} : create log files"
  shell: "touch {{ item }}"
  args:
    creates: "{{ item }}"
  with_items:
    - "{{ php_fpm_errorlog }}"
    - "{{ php_fpm_slowlog }}"
  notify:
    - restart php-fpm

- name: "{{ php_fpm_pool }} : enforce log file permissions"
  file:
    path: "{{ item }}"
    state: file
    owner: "{{ php_fpm_owner }}"
    group: "{{ php_fpm_group }}"
    mode: 0660
  with_items:
    - "{{ php_fpm_errorlog }}"
    - "{{ php_fpm_slowlog }}"
  notify:
    - restart php-fpm

- name: enforce {{ php_fpm_log_dir }} permissions
  file:
    path: "{{ php_fpm_log_dir }}"
    state: directory
    owner: php-fpm
    group: php-fpm
    mode: 0751
  notify:
    - restart php-fpm
