---
- name: "{{ php_fpm_pool }} : create log files"
  shell: "touch {{ item }}"
  args:
    creates: "{{ item }}"
  with_items:
    - "{{ php_fpm_errorlog }}"
    - "{{ php_fpm_slowlog }}"
  notify:
    - restart php-fpm

- name: "{{ php_fpm_pool }} : enforce log file permissions"
  file:
    path: "{{ item }}"
    state: file
    owner: "{{ php_fpm_owner }}"
    group: "{{ php_fpm_group }}"
    mode: 0600
  with_items:
    - "{{ php_fpm_errorlog }}"
    - "{{ php_fpm_slowlog }}"
  notify:
    - restart php-fpm

- name: "{{ php_fpm_pool }} : configure ACL for log access"
  acl:
    path: "{{ php_fpm_log_dir }}"
    entity: "{{ php_fpm_owner }}"
    etype: user
    permissions: rx
    state: present

- name: configure logrotate.d/php-fpm
  template:
    src: logrotate
    dest: /etc/logrotate.d/php-fpm
    owner: root
    group: root
    mode: 0644
  tags: logrotate
