---
- name: install php-fpm
  yum: name=php{{ php_version }}u-fpm

- name: install php modules
  yum: name=php{{ php_version }}u-{{ item }}
  with_items: "{{ php_modules }}"

- name: configure php.ini
  ini_file:
    dest: /etc/php.ini
    section: PHP
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ php_fpm_global_ini }}"
  notify: restart php-fpm

- name: override default php-fpm pool
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0600
  notify: reload php-fpm

- name: configure php-fpm pool
  template:
    src: pool.conf
    dest: /etc/php-fpm.d/{{ php_fpm_pool }}.conf
    owner: root
    group: root
    mode: 0600
  notify: reload php-fpm

- name: start php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes
